#!/bin/bash

string="Performing Checks"
delay=1

while [ 1 ]; do
echo -ne "$string :[ / ]\r"
sleep $delay
echo -ne "$string :[ - ]\r"
sleep $delay
echo -ne "$string :[ \\ ]\r"
sleep $delay
echo -ne "$string :[ | ]\r"
sleep $delay
done
