#!/bin/sh
#
# File: persistent_on
# Descripton: Enable persistent net rules generator; for testing purposes
#
# Copyright (C) 2010-2011, IONICS-EMS Inc.

cd /lib/udev/rules.d/
confirm=`ls | grep 75-persistent-net-generator.rules`

if [ -z $confirm ]; then
echo "udev persistent net rules enabled"
mv /lib/udev/rules.d/disabled/75-persistent-net-generator.rules /lib/udev/rules.d/
else
echo "udev persistent net rules already enabled!"
fi
